version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fb_manpower
      - SECRET_KEY=your-secret-key-for-jwt-please-change-in-production
      - ADMIN_PASSWORD=admin123
    volumes:
      - ./models:/app/models

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fb_manpower
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

